### ISSUE TITLE
Can not execute deployment in migration

### ISSUE THREAD

**Issue by l2dy** [Securrency-OSS/CoralX#4]
## Issue

Can not execute this migration script with CoralX v0.1.0.

```js
const Greeting = artifacts.require("Greeting");

module.exports = async function (deployer) {
  await deployer.deploy(Greeting);
};
```

## Steps to Reproduce

1. `coralX compile`
2. `coralX execute --path migrations`

## Expected Behavior

Migration succeeds.

## Actual Results

```shellsession
% coralX compile

Compiling your contracts...
===========================
> Compiling ./contracts/Greeting.sollc-bin. Attempt #1
> Compilation warnings encountered:

    Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
 --> project:/contracts/Greeting.sol:5:3:
  |
5 |   constructor() public {
  |   ^ (Relevant source part starts here and spans across multiple lines).


> Artifacts written to ~/my-smart-contract/build/contracts
> Compiled successfully using:
   - solc: 0.8.17+commit.8df45f5f.Emscripten.clang
% coralX execute --path migrations
1_deploy_greeting.js

~/.nvm/versions/node/v18.9.0/lib/node_modules/coral-x-fe/dist/coralX.build.js:685
        const ABI = artifacts.getTmpABI();
                              ^
TypeError: artifacts.getTmpABI is not a function
    at Object.deployContract (~/.nvm/versions/node/v18.9.0/lib/node_modules/coral-x-fe/dist/coralX.build.js:685:31)
    at Array.<anonymous> (~/.nvm/versions/node/v18.9.0/lib/node_modules/coral-x-fe/dist/coralX.build.js:662:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _Queue.processQueue (~/.nvm/versions/node/v18.9.0/lib/node_modules/coral-x-fe/dist/coralX.build.js:1115:28)
    at ~/.nvm/versions/node/v18.9.0/lib/node_modules/coral-x-fe/dist/coralX.build.js:678:13
```

## Environment

* Operating System: macOS
* Ethereum client: N/A
* CoralX version (`coralX version`): 0.1.0
* node version (`node --version`): 18.9.0
* npm version (`npm --version`): 8.19.1

**Comment by l2dy** [comment]
Adding a second argument `{ gas: 250000 }` resolved the issue, but this error message is too obscure.
